[package]
name = "async_client_example"
version = "0.1.0"
edition = "2024"

[dependencies]
minifix = { path = "../../crates/minifix", features = ["utils-tokio", "utils-chrono"] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"